mysql:
  image: mysql:5.7.5
  ports:
    - '3306'
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_PASSWORD: root
    MYSQL_USER: root
    MYSQL_DATABASE: multitenant

test:
  build: .
  command: npm run waitdb-test
  volumes:
    - .:/usr/src/app
  links:
    - mysql:db
  environment:
    # DEBUG: knextancy:tenant
