mysql:
  image: mysql:5.7.5
  ports:
    - '3306'
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_PASSWORD: root
    MYSQL_USER: root
    MYSQL_DATABASE: multitenant

test:
  build: .
  command: waitdb-test
  volumes:
    - .:/usr/src/app
  links:
    - mysql:mysql

ci:
  build: .
  command: waitdb-test
  links:
    - mysql:mysql
